require "administrate/base_dashboard"

class AnnonceDashboard < Administrate::BaseDashboard
  # ATTRIBUTE_TYPES
  # a hash that describes the type of each of the model's fields.
  #
  # Each different type represents an Administrate::Field object,
  # which determines how the attribute is displayed
  # on pages throughout the dashboard.
  ATTRIBUTE_TYPES = {
    id: Field::Number,
    photos: Field::ActiveStorage.with_options({url_only: true}),
    designation: Field::String,
    categorie: CategorieField,
    sous_categorie: SousCategorieField,
    pays: PaysselectField,
    ville: Field::String,
    quartier: Field::String,
    je_suis_le: JeSuisLeField,
    tel: Field::String,
    description: TrixField,
    prix: Field::Number,
    commission_agence: Field::Number,
    minimum: NbrmoisselectField,
    condition: Field::String,
    hopital: CheckboxField,
    marche: CheckboxField,
    ecole: CheckboxField,
    service_public: CheckboxField,
    aeroport: CheckboxField,
    supermarche: CheckboxField,
    hotel: CheckboxField,
    bar_restaurant: CheckboxField,
    mairie: CheckboxField,
    centre_de_loisir: CheckboxField,
    pharmacie: CheckboxField,
    pressing: CheckboxField,
    plage: CheckboxField,
    station_d_essence: CheckboxField,
    garage: CheckboxField,
    gare_routiere: CheckboxField,
    nbr_menage: NumberselectField,
    superficie: Field::Number,
    chambre: NumberselectField,
    salon: NumberselectField,
    situe_dans: Field::String,
    cuisine: NumberselectField,
    douche: NumberselectField,
    wc: NumberselectField,
    climatisation: CheckboxField,
    brasseur: CheckboxField,
    parking: CheckboxField,
    electricite: CheckboxField,
    eau: CheckboxField,
    voirie: CheckboxField,
    terrasse: CheckboxField,
    jardin: CheckboxField,
    meubles: CheckboxField,
    cours: CheckboxField,
    machine_a_laver: CheckboxField,
    chauffe_eau_toilette: CheckboxField,
    placards: CheckboxField,
    fibre_optique: CheckboxField,
    adsl:CheckboxField,
    reseaux_mobile: CheckboxField,
    sat: CheckboxField,
    wimax: CheckboxField,
    blr: CheckboxField,
    tv: CheckboxField,
    debarras: CheckboxField,
    caution_electricite_eau: Field::String,
    localisation_longitude: Field::String,
    localisation_latitude: Field::String,
    user_id: UserIdField,
    created_at: Field::DateTime,
    updated_at: Field::DateTime,
    valide: CheckboxField,
    signale: CheckboxField,

  }.freeze

  # COLLECTION_ATTRIBUTES
  # an array of attributes that will be displayed on the model's index page.
  #
  # By default, it's limited to four items to reduce clutter on index pages.
  # Feel free to add, remove, or rearrange items.
  COLLECTION_ATTRIBUTES = [
    :id,
    :designation,
    :sous_categorie,
    :ville,
    :photos
  ].freeze

  # SHOW_PAGE_ATTRIBUTES
  # an array of attributes that will be displayed on the model's show page.
  SHOW_PAGE_ATTRIBUTES = [
    :photos,
    :id,
    :designation,
    :categorie,
    :sous_categorie,
    :pays,
    :ville,
    :quartier,
    :je_suis_le,
    :tel,
    :description,
    :prix,
    :commission_agence,
    :minimum,
    :condition,
    :hopital,
    :marche,
    :ecole,
    :service_public,
    :aeroport,
    :supermarche,
    :hotel,
    :bar_restaurant,
    :mairie,
    :centre_de_loisir,
    :pharmacie,
    :pressing,
    :plage,
    :station_d_essence,
    :garage,
    :gare_routiere,
    :nbr_menage,
    :superficie,
    :chambre,
    :salon,
    :situe_dans,
    :cuisine,
    :douche,
    :wc,
    :climatisation,
    :brasseur,
    :parking,
    :electricite,
    :eau,
    :voirie,
    :terrasse,
    :jardin,
    :meubles,
    :cours,
    :machine_a_laver,
    :chauffe_eau_toilette,
    :placards,
    :fibre_optique,
    :adsl,
    :reseaux_mobile,
    :sat,
    :wimax,
    :blr,
    :tv,
    :debarras,
    :caution_electricite_eau,
    :localisation_longitude,
    :localisation_latitude,
    :user_id,
    :created_at,
    :updated_at,
    :valide,
    :signale,
  ].freeze

  # FORM_ATTRIBUTES
  # an array of attributes that will be displayed
  # on the model's form (`new` and `edit`) pages.
  FORM_ATTRIBUTES = [
    :photos,
    :designation,
    :categorie,
    :sous_categorie,
    :pays,
    :ville,
    :quartier,
    :je_suis_le,
    :tel,
    :description,
    :prix,
    :commission_agence,
    :minimum,
    :condition,
    :hopital,
    :marche,
    :ecole,
    :service_public,
    :aeroport,
    :supermarche,
    :hotel,
    :bar_restaurant,
    :mairie,
    :centre_de_loisir,
    :pharmacie,
    :pressing,
    :plage,
    :station_d_essence,
    :garage,
    :gare_routiere,
    :nbr_menage,
    :superficie,
    :chambre,
    :salon,
    :situe_dans,
    :cuisine,
    :douche,
    :wc,
    :climatisation,
    :brasseur,
    :parking,
    :electricite,
    :eau,
    :voirie,
    :terrasse,
    :jardin,
    :meubles,
    :cours,
    :machine_a_laver,
    :chauffe_eau_toilette,
    :placards,
    :fibre_optique,
    :adsl,
    :reseaux_mobile,
    :sat,
    :wimax,
    :blr,
    :tv,
    :debarras,
    :caution_electricite_eau,
    :localisation_longitude,
    :localisation_latitude,
    :user_id,
    :valide,
    :signale,
  ].freeze

  # Overwrite this method to customize how annonces are displayed
  # across all pages of the admin dashboard.
  #
  def display_resource(annonce)
    #"Annonce ##{annonce.id}"
     annonce.designation
  end
end
